PROJNAME=bot
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/cygwin/home/smihica/code/smapo/beacon/bot/bot
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS= delay.asm
LIBASMSRCS= psocconfig.asm psocconfigtbl.asm pwm16_1.asm pwm16_1int.asm pwm16_2.asm pwm16_2int.asm pwm16_3.asm pwm16_3int.asm pwm16_4.asm pwm16_4int.asm uart_1.asm uart_1int.asm uart_1plus.asm uart_2.asm uart_2int.asm uart_2plus.asm
STDASMSRCS=
OBJECT_SOURCES= delay.asm main.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=bot 
